const OLD='quiet-notes-v1',DB='quiet-notes',$=s=>document.querySelector(s);let db,notes=[],current,view='all',tag='',saveTimer,config={},key;
const uid=()=>crypto.randomUUID(),now=()=>Date.now(),safe=s=>String(s??'').replace(/[<>]/g,''),enc=new TextEncoder,dec=new TextDecoder;
const b64=x=>btoa(String.fromCharCode(...new Uint8Array(x))),raw=x=>Uint8Array.from(atob(x),c=>c.charCodeAt(0));
function toast(x){let t=$('#toast');t.textContent=x;t.hidden=false;setTimeout(()=>t.hidden=true,2500)}
function req(r){return new Promise((y,n)=>{r.onsuccess=()=>y(r.result);r.onerror=()=>n(r.error)})}function store(n,m='readonly'){return db.transaction(n,m).objectStore(n)}
function open(){return new Promise((y,n)=>{let r=indexedDB.open(DB,2);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains('notes'))d.createObjectStore('notes',{keyPath:'id'});if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta',{keyPath:'key'})};r.onsuccess=()=>y(r.result);r.onerror=()=>n(r.error)})}
async function meta(k,v){await req(store('meta','readwrite').put({key:k,value:v}))}async function get(k){return(await req(store('meta').get(k)))?.value}
async function derive(p,s){return crypto.subtle.deriveKey({name:'PBKDF2',salt:s,iterations:250000,hash:'SHA-256'},await crypto.subtle.importKey('raw',enc.encode(p),'PBKDF2',false,['deriveKey']),{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encrypt(n){let iv=crypto.getRandomValues(new Uint8Array(12)),d=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(n)));return{id:n.id,secure:true,iv:b64(iv),data:b64(d)}}async function decrypt(r){return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:raw(r.iv)},key,raw(r.data))))}
async function migrate(){if(await get('migrated'))return;let old;try{old=JSON.parse(localStorage.getItem(OLD)||'null')}catch{}if(Array.isArray(old)){for(let n of old)if(n?.id){n={id:n.id,title:safe(n.title)||'Untitled',body:safe(n.body),tags:Array.isArray(n.tags)?n.tags.map(safe):[],pinned:!!n.pinned,archived:false,trashed:false,locked:false,createdAt:n.updatedAt||now(),updatedAt:n.updatedAt||now()};await req(store('notes','readwrite').put({id:n.id,plain:n}))}await meta('legacy-backup',old);localStorage.removeItem(OLD)}await meta('migrated',true)}
async function load(){notes=[];for(let r of await req(store('notes').getAll()))try{notes.push(r.secure?await decrypt(r):r.plain)}catch{toast('A protected note could not be read.')}notes.sort((a,b)=>b.updatedAt-a.updatedAt)}
async function persist(n){n.updatedAt=now();$('#status').textContent='Saving…';try{await req(store('notes','readwrite').put(config.protected?await encrypt(n):{id:n.id,plain:n}));let i=notes.findIndex(x=>x.id===n.id);i<0?notes.unshift(n):notes[i]=n;$('#status').textContent='Saved';render()}catch(e){$('#status').textContent='Offline';toast('Saving failed; keep this tab open.')}}
function matches(n){let q=$('#search').value.toLowerCase();if(view==='all'&&(n.archived||n.trashed))return false;if(view==='pinned'&&(!n.pinned||n.archived||n.trashed))return false;if(view==='archive'&&(!n.archived||n.trashed))return false;if(view==='trash'&&!n.trashed)return false;if(tag&&!n.tags.includes(tag))return false;if(q&&(n.locked&&config.privateMode||![n.title,n.body,...n.tags].join(' ').toLowerCase().includes(q)))return false;return true}
function render(){let cs={all:0,pinned:0,archive:0,trash:0};notes.forEach(n=>{if(n.trashed)cs.trash++;else if(n.archived)cs.archive++;else{cs.all++;if(n.pinned)cs.pinned++}});for(let k in cs)$('#'+({all:'allC',pinned:'pinC',archive:'arcC',trash:'trashC'}[k])).textContent=cs[k];let title={all:'All Notes',pinned:'Pinned',archive:'Archive',trash:'Trash'}[view];$('#viewTitle').textContent=tag?'#'+tag:title;document.querySelectorAll('[data-v]').forEach(b=>b.classList.toggle('active',b.dataset.v===view&&!tag));let list=notes.filter(matches).sort((a,b)=>+b.pinned-+a.pinned||b.updatedAt-a.updatedAt),box=$('#notes');box.innerHTML='';list.forEach(n=>{let b=document.createElement('button');b.className='note '+(current?.id===n.id?'active':'');b.innerHTML=`<h2>${n.locked&&config.privateMode?'Locked note':safe(n.title)}</h2><p>${n.locked&&config.privateMode?'Private content':safe(n.body)}</p><small>${new Date(n.updatedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})} ${n.tags.map(x=>'#'+safe(x)).join(' ')}</small>${n.pinned?'<i>⌖</i>':''}`;b.onclick=()=>{current=n;$('#app').classList.add('editing');render()};box.append(b)});$('#empty').hidden=!!list.length;let ts=[...new Set(notes.filter(n=>!n.trashed).flatMap(n=>n.tags))];$('#tagsList').innerHTML='';ts.forEach(x=>{let b=document.createElement('button');b.textContent=x;b.onclick=()=>{tag=x;view='all';render()};$('#tagsList').append(b)});let has=!!current;$('#editor').hidden=!has;$('#noNote').hidden=has;if(has){$('#title').value=current.title;$('#body').value=current.body;$('#tags').value=current.tags.join(', ');stats()}}
function make(){current={id:uid(),title:'',body:'',tags:[],pinned:false,archived:false,trashed:false,locked:false,createdAt:now(),updatedAt:now()};$('#app').classList.add('editing');render();$('#title').focus()}function edit(){if(!current)return;current.title=$('#title').value||'Untitled';current.body=$('#body').value;current.tags=[...new Set($('#tags').value.split(',').map(x=>x.trim().replace(/^#/, '')).filter(Boolean))];stats();clearTimeout(saveTimer);saveTimer=setTimeout(()=>persist(current),500)}function stats(){let b=$('#body').value.trim();$('#stats').textContent=`${b?b.split(/\s+/).length:0} words · ${b.length} characters`}
async function move(){if(!current)return;current.trashed=true;await persist(current);current=null;render();toast('Moved to Trash')}async function archive(){if(current){current.archived=!current.archived;await persist(current);toast(current.archived?'Archived':'Restored')}}async function pin(){if(current){current.pinned=!current.pinned;await persist(current)}}
function modal(title,body,actions){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;let f=$('#modalFoot');f.innerHTML='';actions.forEach(([x,fn,cl])=>{let b=document.createElement('button');b.textContent=x;b.className=cl||'';b.type='button';b.onclick=()=>{fn();$('#modal').close()};f.append(b)});$('#modal').showModal()}
function settings(){modal('Settings',`<label>Theme<select id="theme"><option>light</option><option>dark</option><option>sepia</option></select></label><label><input id="private" type="checkbox"> Hide locked-note details</label><p>Notes stay in this browser. Password protection encrypts notes at rest; a forgotten password cannot be recovered.</p><button id="protect" type="button">${config.protected?'Password protection enabled':'Enable password protection'}</button><button id="export" type="button">Export JSON backup</button>`,[['Close',()=>{}]]);$('#theme').value=config.theme||'light';$('#private').checked=!!config.privateMode;$('#theme').onchange=async e=>{config.theme=e.target.value;document.documentElement.dataset.theme=config.theme;await meta('config',config)};$('#private').onchange=async e=>{config.privateMode=e.target.checked;await meta('config',config)};$('#protect').onclick=protect;$('#export').onclick=backup}
function protect(){modal('Encrypt your notes',`<p>Use a unique password of at least 10 characters. It cannot be recovered.</p><label>Password<input id="p1" type="password"></label><label>Confirm password<input id="p2" type="password"></label>`,[['Cancel',()=>{}],['Enable',async()=>{let p=$('#p1').value;if(p.length<10||p!==$('#p2').value)return toast('Passwords must match and be at least 10 characters.');let salt=crypto.getRandomValues(new Uint8Array(16));key=await derive(p,salt);let check=await encrypt({id:'check',value:'quiet-notes'});config={...config,protected:true,salt:b64(salt),check};await meta('config',config);for(let n of notes)await persist(n);toast('Encrypted at rest.')}]] )}
async function unlock(p){try{key=await derive(p,raw(config.salt));let c=await decrypt(config.check);if(c.value!=='quiet-notes')throw 0;$('#lock').hidden=true;$('#app').hidden=false;await load();render()}catch{$('#lockText').textContent='Wrong password. Please try again.'}}
function lock(){if(!config.protected)return toast('Enable password protection in Settings.');key=null;notes=[];current=null;$('#app').hidden=true;$('#lock').hidden=false;$('#password').value=''}function backup(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({format:'quiet-notes-json',version:2,notes})],{type:'application/json'}));a.download='quiet-notes-backup.json';a.click();toast('Backup downloaded.')}
function command(){let a=[['Create note',make],['Search notes',()=>$('#search').focus()],['Lock app',lock],['Settings',settings],['Export backup',backup],['Pinned',()=>{view='pinned';render()}],['Archive',()=>{view='archive';render()}],['Trash',()=>{view='trash';render()}]];let b=$('#commandList');b.innerHTML='';a.forEach(([x,f])=>{let q=document.createElement('button');q.className='command';q.textContent=x;q.onclick=()=>{$('#commands').close();f()};b.append(q)});$('#commands').showModal();$('#commandSearch').focus()}
async function boot(){try{if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});db=await open();config=await get('config')||{};document.documentElement.dataset.theme=config.theme||'light';await migrate();if(config.protected){$('#lock').hidden=false}else{$('#app').hidden=false;await load();render()}}catch(e){document.body.innerHTML='<h1>Quiet Notes could not open browser storage.</h1>'}}
document.addEventListener('click',e=>{let a=e.target.closest('[data-a]')?.dataset.a;({new:make,settings,lock,command,pin,archive,trash:move,duplicate:async()=>{if(current){let n={...current,id:uid(),title:current.title+' copy'};await persist(n);current=n;render()}},menu:()=>$('#app').classList.toggle('menu'),back:()=>$('#app').classList.remove('editing'),focus:()=>$('#edit').classList.toggle('focus')})[a]?.()});document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{view=b.dataset.v;tag='';render()});['title','body','tags'].forEach(x=>$('#'+x).oninput=edit);$('#search').oninput=render;$('#unlock').onsubmit=e=>{e.preventDefault();unlock($('#password').value)};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();command()}if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();edit();persist(current)}if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus()}if(e.key.toLowerCase()==='n'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();make()}if(e.key==='Escape')$('#app').classList.remove('editing','menu')});boot();
